// apps/micro-react/src/views/Home.tsx
import { Link } from 'react-router-dom'

const Home = () => {
  return (
    <div style={{ padding: '2rem' }}>
      <h1>首页</h1>
      <p>这是 React 子应用的首页</p>
      <div style={{ marginTop: '1rem', display: 'flex', gap: '1rem' }}>
        <Link
          to="/page1"
          style={{
            padding: '0.5rem 1rem',
            background: '#007bff',
            color: 'white',
            textDecoration: 'none',
            borderRadius: '4px',
          }}
        >
          跳转到页面1
        </Link>
        <Link
          to="/page2"
          style={{
            padding: '0.5rem 1rem',
            background: '#007bff',
            color: 'white',
            textDecoration: 'none',
            borderRadius: '4px',
          }}
        >
          跳转到页面2
        </Link>
        <Link
          to="/detail"
          style={{
            padding: '0.5rem 1rem',
            background: '#007bff',
            color: 'white',
            textDecoration: 'none',
            borderRadius: '4px',
          }}
        >
          查看详情
        </Link>
      </div>
    </div>
  )
}

export default Home

// apps/micro-vue/src/views/Home.vue
<template>
  <div class="home">
    <h1>首页</h1>
    <p>这是 Vue 子应用的首页</p>
    <div class="actions">
      <router-link to="/page1">跳转到页面1</router-link>
      <router-link to="/page2">跳转到页面2</router-link>
      <router-link to="/detail">查看详情</router-link>
    </div>
  </div>
</template>

<script setup lang="ts">
// Home 页面
</script>

<style scoped>
.home {
  padding: 2rem;
}

.actions {
  margin-top: 1rem;
  display: flex;
  gap: 1rem;
}

.actions a {
  padding: 0.5rem 1rem;
  background: #007bff;
  color: white;
  text-decoration: none;
  border-radius: 4px;
  transition: background 0.2s;
}

.actions a:hover {
  background: #0056b3;
}
</style>
