// apps/micro-vue/src/App.vue
<template>
  <div class="app">
    <nav class="navbar">
      <h1>Vue 子应用</h1>
      <div class="nav-links">
        <router-link to="/">首页</router-link>
        <router-link to="/page1">页面1</router-link>
        <router-link to="/page2">页面2</router-link>
        <router-link to="/detail">详情</router-link>
        <router-link to="/settings">设置</router-link>
      </div>
    </nav>
    <div class="content">
      <div class="info">
        <p>当前路由: {{ $route.fullPath }}</p>
        <p>应用名称: {{ appName }}</p>
        <p>计数: {{ count }}</p>
      </div>
      <div class="actions">
        <button @click="increment">增加计数</button>
        <button @click="sendMessage">发送事件</button>
        <button @click="sendRequest">发送请求</button>
      </div>
      <router-view />
      <div class="features">
        <h2>功能演示</h2>
        <ul>
          <li>生命周期管理：应用已挂载</li>
          <li>Vue Router 集成：使用 vue-router 进行路由管理</li>
          <li>路由同步：路由变化自动同步到主应用</li>
          <li>通信功能：可以发送事件和请求</li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import type { MicroApp } from '@micro-iframe/sdk'

interface Props {
  microApp: MicroApp
}

const props = defineProps<Props>()
const route = useRoute()

const count = ref(0)
const appName = ref('')

onMounted(() => {
  const propsData = props.microApp.getCurrentProps()
  appName.value = propsData?.name || 'N/A'
})

const increment = () => {
  count.value++
}

const sendMessage = () => {
  props.microApp.communication.emit('test-event', {
    message: 'Hello from Vue App!',
    count: count.value,
  })
}

const sendRequest = async () => {
  try {
    const result = await props.microApp.communication.request('test-method', {
      param: 'test',
    })
    console.log('请求结果:', result)
    alert(`请求成功: ${JSON.stringify(result)}`)
  } catch (error) {
    console.error('请求失败:', error)
    alert(`请求失败: ${error}`)
  }
}
</script>

<style scoped>
.app {
  font-family: Arial, sans-serif;
}

.navbar {
  background: #f8f9fa;
  padding: 1rem 2rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid #dee2e6;
}

.navbar h1 {
  margin: 0;
  font-size: 1.5rem;
}

.nav-links {
  display: flex;
  gap: 1rem;
}

.nav-links a {
  padding: 0.5rem 1rem;
  text-decoration: none;
  color: #007bff;
  border-radius: 4px;
  transition: background 0.2s;
}

.nav-links a:hover,
.nav-links a.router-link-active {
  background: #e9ecef;
  color: #0056b3;
}

.content {
  padding: 2rem;
}

.info {
  margin-bottom: 1rem;
  padding: 1rem;
  background: #f8f9fa;
  border-radius: 4px;
}

.actions {
  margin-bottom: 2rem;
  display: flex;
  gap: 1rem;
}

button {
  padding: 0.5rem 1rem;
  cursor: pointer;
  border: 1px solid #ccc;
  border-radius: 4px;
  background: #fff;
  transition: background 0.2s;
}

button:hover {
  background: #f0f0f0;
}

.features {
  margin-top: 2rem;
  padding-top: 2rem;
  border-top: 1px solid #dee2e6;
}

ul {
  list-style-type: disc;
  padding-left: 2rem;
}
</style>

// apps/micro-react/src/App.tsx
import React, { useState, useEffect, useRef } from 'react'
import { Outlet, useLocation, NavLink, useNavigate } from 'react-router-dom'
import type { MicroApp } from '@micro-iframe/sdk'
import { createUseRouteSync, type ReactRouterDependencies } from '@micro-iframe/sdk'

// 创建路由同步 Hook
const useRouteSync = createUseRouteSync({
  useLocation,
  useNavigate,
  useEffect,
  useRef,
})

interface AppProps {
  microApp: MicroApp
}

const App: React.FC<AppProps> = ({ microApp }) => {
  const [count, setCount] = useState(0)
  const location = useLocation()

  // 使用 Hook 自动处理路由同步
  useRouteSync(microApp)

  const handleSendMessage = () => {
    microApp.communication.emit('test-event', {
      message: 'Hello from React App!',
      count,
    })
  }

  const handleRequest = async () => {
    try {
      const result = await microApp.communication.request('test-method', {
        param: 'test',
      })
      console.log('请求结果:', result)
      alert(`请求成功: ${JSON.stringify(result)}`)
    } catch (error) {
      console.error('请求失败:', error)
      alert(`请求失败: ${error}`)
    }
  }

  const props = microApp.getCurrentProps()

  return (
    <div
      style={{
        fontFamily: 'Arial, sans-serif',
      }}
    >
      <nav
        style={{
          background: '#f8f9fa',
          padding: '1rem 2rem',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          borderBottom: '1px solid #dee2e6',
        }}
      >
        <h1 style={{ margin: 0, fontSize: '1.5rem' }}>React 子应用</h1>
        <div style={{ display: 'flex', gap: '1rem' }}>
          <NavLink
            to="/"
            style={({ isActive }) => ({
              padding: '0.5rem 1rem',
              textDecoration: 'none',
              color: isActive ? '#fff' : '#007bff',
              background: isActive ? '#007bff' : 'transparent',
              borderRadius: '4px',
            })}
          >
            首页
          </NavLink>
          <NavLink
            to="/page1"
            style={({ isActive }) => ({
              padding: '0.5rem 1rem',
              textDecoration: 'none',
              color: isActive ? '#fff' : '#007bff',
              background: isActive ? '#007bff' : 'transparent',
              borderRadius: '4px',
            })}
          >
            页面1
          </NavLink>
          <NavLink
            to="/page2"
            style={({ isActive }) => ({
              padding: '0.5rem 1rem',
              textDecoration: 'none',
              color: isActive ? '#fff' : '#007bff',
              background: isActive ? '#007bff' : 'transparent',
              borderRadius: '4px',
            })}
          >
            页面2
          </NavLink>
          <NavLink
            to="/detail"
            style={({ isActive }) => ({
              padding: '0.5rem 1rem',
              textDecoration: 'none',
              color: isActive ? '#fff' : '#007bff',
              background: isActive ? '#007bff' : 'transparent',
              borderRadius: '4px',
            })}
          >
            详情
          </NavLink>
          <NavLink
            to="/settings"
            style={({ isActive }) => ({
              padding: '0.5rem 1rem',
              textDecoration: 'none',
              color: isActive ? '#fff' : '#007bff',
              background: isActive ? '#007bff' : 'transparent',
              borderRadius: '4px',
            })}
          >
            设置
          </NavLink>
        </div>
      </nav>
      <div style={{ padding: '2rem' }}>
        <div
          style={{
            marginBottom: '1rem',
            padding: '1rem',
            background: '#f8f9fa',
            borderRadius: '4px',
          }}
        >
          <p>当前路由: {location.pathname}</p>
          <p>应用名称: {props?.name || 'N/A'}</p>
          <p>计数: {count}</p>
        </div>
        <div style={{ marginBottom: '2rem', display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
          <button onClick={() => setCount(count + 1)}>增加计数</button>
          <button onClick={handleSendMessage}>发送事件</button>
          <button onClick={handleRequest}>发送请求</button>
        </div>
        <Outlet />
        <div
          style={{
            marginTop: '2rem',
            paddingTop: '2rem',
            borderTop: '1px solid #dee2e6',
          }}
        >
          <h2>功能演示</h2>
          <ul>
            <li>生命周期管理：应用已挂载</li>
            <li>React Router 集成：使用 react-router-dom 进行路由管理</li>
            <li>路由同步：路由变化自动同步到主应用</li>
            <li>通信功能：可以发送事件和请求</li>
          </ul>
        </div>
      </div>
    </div>
  )
}

export default App
